# Generated by Django 6.0.6 on 2026-06-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('source', 'Source'), ('config', 'Configuration'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=50)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(help_text='Taille en octets')),
                ('description', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repositories.repository')),
            ],
        ),
    ]
